using AussieCake.Question;
using System.Collections.Generic;
using System.Linq;

namespace AussieCake.Templates
{
    public class TemplateEssay : Template
    {
        public static List<IQuest> Words = new List<IQuest>()
        {
            new EssayVM(0, "The", true),
            new EssayVM(1, "importance", true),
            new EssayVM(2, "of"),
            new EssayVM(3, "topic"),
            new EssayVM(4, ","),
            new EssayVM(5, "which"),
            new EssayVM(6, "was"),
            new EssayVM(7, "always"),
            new EssayVM(8, "debatable"),
            new EssayVM(9, ","),
            new EssayVM(10, "has"),
            new EssayVM(11, "now"),
            new EssayVM(12, "become"),
            new EssayVM(13, "more"),
            new EssayVM(14, "controversial"),
            new EssayVM(15, "."),
            new EssayVM(16, "It", true),
            new EssayVM(17, "is", true),
            new EssayVM(18, "widely", true),
            new EssayVM(19, "accepted"),
            new EssayVM(20, "that"),
            new EssayVM(21, "topic"),
            new EssayVM(22, "has"),
            new EssayVM(23, "some"),
            new EssayVM(24, "favourable"),
            new EssayVM(25, "arguments"),
            new EssayVM(26, ";"),
            new EssayVM(27, "however"),
            new EssayVM(28, ","),
            new EssayVM(29, "there", true),
            new EssayVM(30, "has", true),
            new EssayVM(31, "always", true),
            new EssayVM(32, "been"),
            new EssayVM(33, "some"),
            new EssayVM(34, "contention"),
            new EssayVM(35, "about"),
            new EssayVM(36, "it"),
            new EssayVM(37, "."),
            new EssayVM(38, "This", true),
            new EssayVM(39, "essay", true),
            new EssayVM(40, "will"),
            new EssayVM(41, "elaborate"),
            new EssayVM(42, "on"),
            new EssayVM(43, "the"),
            new EssayVM(44, "motives"),
            new EssayVM(45, "why"),
            new EssayVM(46, "I"),
            new EssayVM(47, "strongly"),
            new EssayVM(48, "agree"),
            new EssayVM(49, "that"),
            new EssayVM(50, "the"),
            new EssayVM(51, "benefits"),
            new EssayVM(52, "of"),
            new EssayVM(53, "topic"),
            new EssayVM(54, "outweigh"),
            new EssayVM(55, "the"),
            new EssayVM(56, "risks"),
            new EssayVM(57, "."),
            new EssayVM(58, Paragraph),
            new EssayVM(59, "At", true),
            new EssayVM(60, "the", true),
            new EssayVM(61, "outset"),
            new EssayVM(62, ","),
            new EssayVM(63, "there"),
            new EssayVM(64, "are"),
            new EssayVM(65, "numerous"),
            new EssayVM(66, "reasons"),
            new EssayVM(67, "why"),
            new EssayVM(68, "topic"),
            new EssayVM(69, "has"),
            new EssayVM(70, "some"),
            new EssayVM(71, "negative"),
            new EssayVM(72, "aspects"),
            new EssayVM(73, ","),
            new EssayVM(74, "but", true),
            new EssayVM(75, "the", true),
            new EssayVM(76, "most", true),
            new EssayVM(77, "alarming"),
            new EssayVM(78, "one"),
            new EssayVM(79, "lies"),
            new EssayVM(80, "in"),
            new EssayVM(81, "the"),
            new EssayVM(82, "fact"),
            new EssayVM(83, "it"),
            new EssayVM(84, "can"),
            new EssayVM(85, "cause"),
            new EssayVM(86, "xxx"),
            new EssayVM(87, ";"),
            new EssayVM(88, "therefore", true),
            new EssayVM(89, ","),
            new EssayVM(90, "this", true),
            new EssayVM(91, "can", true),
            new EssayVM(92, "be", true),
            new EssayVM(93, "a", true),
            new EssayVM(94, "contributing"),
            new EssayVM(95, "factor"),
            new EssayVM(96, "to"),
            new EssayVM(97, "the"),
            new EssayVM(98, "increase"),
            new EssayVM(99, "of"),
            new EssayVM(100, "xxx"),
            new EssayVM(101, "in"),
            new EssayVM(102, "Australia"),
            new EssayVM(103, "."),
            new EssayVM(104, "For", true),
            new EssayVM(105, "instance"),
            new EssayVM(106, ","),
            new EssayVM(107, "scientists", true),
            new EssayVM(108, "discover"),
            new EssayVM(109, "that"),
            new EssayVM(110, "the"),
            new EssayVM(111, "local"),
            new EssayVM(112, "community"),
            new EssayVM(113, "is"),
            new EssayVM(114, "directly"),
            new EssayVM(115, "affected"),
            new EssayVM(116, "by"),
            new EssayVM(117, "the"),
            new EssayVM(118, "absence"),
            new EssayVM(119, "of"),
            new EssayVM(120, "xxx"),
            new EssayVM(121, "."),
            new EssayVM(122, Paragraph),
            new EssayVM(123, "Nevertheless", true),
            new EssayVM(124, ","),
            new EssayVM(125, "some"),
            new EssayVM(126, "people"),
            new EssayVM(127, "adopt"),
            new EssayVM(128, "an"),
            new EssayVM(129, "opposing"),
            new EssayVM(130, "view"),
            new EssayVM(131, "and", true),
            new EssayVM(132, "tend", true),
            new EssayVM(133, "to"),
            new EssayVM(134, "believe"),
            new EssayVM(135, "that"),
            new EssayVM(136, "topic"),
            new EssayVM(137, "has"),
            new EssayVM(138, "innumerable"),
            new EssayVM(139, "facts"),
            new EssayVM(140, "in"),
            new EssayVM(141, "favour"),
            new EssayVM(142, "of"),
            new EssayVM(143, "xxx"),
            new EssayVM(144, "."),
            new EssayVM(145, "In", true),
            new EssayVM(146, "addition"),
            new EssayVM(147, ","),
            new EssayVM(148, "xxx"),
            new EssayVM(149, "play", true),
            new EssayVM(150, "an"),
            new EssayVM(151, "important"),
            new EssayVM(152, "role"),
            new EssayVM(153, "in"),
            new EssayVM(154, "modern"),
            new EssayVM(155, "society"),
            new EssayVM(156, "."),
            new EssayVM(157, "As", true),
            new EssayVM(158, "an"),
            new EssayVM(159, "illustration"),
            new EssayVM(160, ","),
            new EssayVM(161, "some", true),
            new EssayVM(162, "studies"),
            new EssayVM(163, "reveal"),
            new EssayVM(164, "that"),
            new EssayVM(165, "citizens"),
            new EssayVM(166, "of"),
            new EssayVM(167, "New"),
            new EssayVM(168, "Zealand"),
            new EssayVM(169, "can"),
            new EssayVM(170, "take"),
            new EssayVM(171, "advantage"),
            new EssayVM(172, "of"),
            new EssayVM(173, "xxx"),
            new EssayVM(174, "."),
            new EssayVM(175, Paragraph),
            new EssayVM(176, "From", true),
            new EssayVM(177, "what", true),
            new EssayVM(178, "has"),
            new EssayVM(179, "been"),
            new EssayVM(180, "discussed"),
            new EssayVM(181, "above"),
            new EssayVM(182, ","),
            new EssayVM(183, "it"),
            new EssayVM(184, "can"),
            new EssayVM(185, "be"),
            new EssayVM(186, "concluded"),
            new EssayVM(187, "that"),
            new EssayVM(188, "the", true),
            new EssayVM(189, "effects", true),
            new EssayVM(190, "of"),
            new EssayVM(191, "topic"),
            new EssayVM(192, "are"),
            new EssayVM(193, "undeniable"),
            new EssayVM(194, "since", true),
            new EssayVM(195, "it"),
            new EssayVM(196, "has"),
            new EssayVM(197, "a"),
            new EssayVM(198, "profound"),
            new EssayVM(199, "impact"),
            new EssayVM(200, "on"),
            new EssayVM(201, "xxx"),
            new EssayVM(202, ";"),
            new EssayVM(203, "however", true),
            new EssayVM(204, ","),
            new EssayVM(205, "the"),
            new EssayVM(206, "way"),
            new EssayVM(207, "it"),
            new EssayVM(208, "affects"),
            new EssayVM(209, "xxx"),
            new EssayVM(210, "should"),
            new EssayVM(211, "not"),
            new EssayVM(212, "be"),
            new EssayVM(213, "overlooked"),
            new EssayVM(214, "."),

        };
    }
}
